[Server]
Host="0.0.0.0"
Port="8080"
ShutdownTimeout="30s"

[DB]
type="postgresql"
[DB.Postgres]
Host="db"
Port="5432"
User="petstore"
Password="emptypassword"
DBName="petstore"
SSLMode="disable"

[Workers.Invoice]
count=1
interval="30s"

[Auth]
type="jwt"

[Storage]
type="minio"
[Storage.Minio]
Host="minio"
Port="9000"
AccessKey="AKIAIOSFODNN7EXAMPLE"
SecretKey="wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
ssl=false
