version: '3'
services:

  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_DB: petstore
      POSTGRES_USER: petstore
      POSTGRES_PASSWORD: emptypassword
    ports:
      - "5432:5432"

  minio:
    container_name: minio
    image: minio/minio:RELEASE.2019-09-05T23-24-38Z
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: minio server /minio/data


    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  app:
    container_name: app
    build: .
    command: ./wait-for-it.sh db:5432 -- go run main.go && fresh
    volumes:
      - .:/go/src/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
      - minio

